name: Build ROM

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Systempackete aktualisieren
        run: |
          sudo apt update
          sudo ACCEPT_EULA=Y apt -y --fix-missing --allow-downgrades upgrade
          sudo apt -y --allow-downgrades install make g++-10 bison git python-is-python3 python3-pip bison pkg-config libpng-dev
          sudo pip install pypng

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: RGBDS auschecken
        uses: actions/checkout@v4
        with:
          repository: gbdev/rgbds
          path: rgbds
          ref: 'v0.6.1'

      - name: RGBDS installieren
        run: |
          cd rgbds
          make Q=
          sudo make install

      - name: Make
        if: ${{ github.repository_owner != 'pret' }}
        run: |
          make all

      - name: ROM hochladen
        uses: actions/upload-artifact@v4
        with:
          name: roms
          path: |
            pokecrystal.gbc
            pokecrystal11.gbc
            pokecrystal_debug.gbc
            pokecrystal11_debug.gbc
